const routes = {
  dashboard: "/dashboard",
  login: "/login",
  signup: "/signup",
  home: "/home",
  ErrorPage: "/404",
  registration: '/registration',
  // welcome: "/welcome",
  welcome: "/welcome/:id_token?",
  welcome1: "/welcome",
  profile: "/profile",
  password: '/changepassword',
  createpassword: '/createpassword',
  newcardinfo: "/newcard",
  cardinfotable: "/cardinfotable",
  balanceinfotable: "/balanceinfo",
  setpininfotable: "/set_pin_table",
  managecardinfotable: "/Manage_cardinfo_table",
  managecardstatus: "/card_status",
  setpintable: "/setpin_table",
  setpinstatus: "/setpin_status",
  changepintable: "/changepin_table",
  changepinstatus: "/changepin_status",
  forgotremember: "/forgot_pin",
  transactiontable: "/Transaction_table",
  transactionfilter: "/Transaction_filter",
  tansactionfilterdetails: "/Transaction_filter_details",
  channelenable: "/channel_enablement",
  limit: "/limit_Management",
  editmyprofile: "/edit_profile",
  registrationSucess: "/passwordSuccess",
  success: "/success"
};
export default routes;
